name: Swagger Doc

on:
  push:
    branches:
      - main

jobs:
  swagger-doc:
    runs-on: ubuntu-20.04  # Alteramos de ubuntu-latest para uma versão específica
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: go get github.com/swaggo/swag/cmd/swag

      - name: Generate Swagger Doc
        run: swag init -g ./main.go --output ./output  # Certifique-se de que o comando está correto

      - name: Deploy documentation
        uses: actions/deploy-pages@v2.4.1
        with:
          token: ${{ secrets.GH_TOKEN }}
          branch: gh-pages  # Certifique-se de que esta configuração está correta
