name: Swagger Doc

on:
  push:
    branches:
      - main

jobs:
  swagger-doc:
    runs-on: ubuntu-20.04  # Mantemos a alteração para uma versão específica
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: go get github.com/swaggo/swag/cmd/swag

      - name: Generate Swagger Doc
        run: swag init -g ./main.go --output ./output  # Certifique-se de que o comando está correto

      - name: Deploy documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./output
