name: Swagger Doc

on:
  push:
    branches:
      - main

jobs:
  swagger-doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: go get ./...

      - name: Generate Swagger Doc
        env:
          GOOS: "json"
        run: swagger generate --yaml --output output/swagger.json

      - name: Deploy documentation
        uses: gh-pages@1.1
        with:
          repo_token: ${{ secrets.GH_TOKEN }}
          ref: main